from django.urls import path # type: ignore
from home import views
from django.views.generic.base import TemplateView # type: ignore

urlpatterns = [
  path('', views.index, name='index'),
    path('gallery/', views.gallery_view, name='gallery'),
    path('about/', views.about_page, name='about'),
    path('contact/', views.contact, name='contact'),
    path('services/', views.services, name='services'),
    path('seo/', views.seo, name='seo'),
    path('thumbnails/', views.thumbnails, name='thumbnails'),
    path('digitalmarketing/', views.digitalmarketing, name='digitalmarketing'),
    path('search/', views.search, name='search'),
    path('myadmin/', views.custom_admin, name='custom_admin'),
    path('german.html', views.german_view, name='german'),
    path('other-topics.html', views.otherTopics, name='other_topics'),
   
    # Topic routes
    path('nouns.html', views.nouns_view, name='nouns'),
    path('articles.html', views.articles_view, name='articles'),
    path('adjectives.html', views.adjectives_view, name='adjectives'),
    path('conjugation.html', views.conjugation_view, name='conjugation'),
    path('cases.html', views.cases_view, name='cases'),
    path('prepositions.html', views.prepositions_view, name='prepositions'),
    path('structure.html', views.structure_view, name='structure'),
    path('listening.html', views.listening_view, name='listening'),
    path('writing.html', views.writing_view, name='writing'),
    path('speaking.html', views.speaking_view, name='speaking'),
    path('culture.html', views.culture_view, name='culture'),
    path('exam.html', views.exam_view, name='exam'),
    path('personal-pronouns.html', views.personal_pronouns_view, name='personal-pronouns'),
    path('verbs-wfrage-ja-nein-normaler.html', views.verbs_wfrage_ja_nein_normaler_view, name='verbs_wfrage_ja_nein_normaler'),
   path('imperative.html', views.imperative_view, name='imperative'),
     path('akkusative.html', views.akkusative_view, name='akkusative'),
    path('possessive.html', views.possessive_view, name='possessive'),
   path('modalverbpresent.html', views.modalverbpresent_view, name='modalverbpresent'),
  path('praterituma1.html', views.praterituma1_view, name='praterituma1'),
  path('trennbare.html', views.trennbare_view, name='trennbare'),
    path('dative.html', views.dative_view, name='dative'),
     path('wechsel.html', views.wechsel_view, name='wechsel'),
      path('partizip2.html', views.partizip2_view, name='partizip2'),
       path('welcherdieser.html', views.welcherdieser_view, name='welcherdieser'),
       path('deshalbtrotzdem.html', views.deshalbtrotzdem_view, name='deshalbtrotzdem'),
    path('a2-topics.html', views.a2topics_view, name='a2-topics'),
   path('doch.html', views.doch_view, name='doch'),
 path('reflexive.html', views.reflexive_view, name='reflexive'),
  path('weil.html', views.weil_view, name='weil'),
    path('modal_prateritum.html', views.modal_prateritum_view, name='modal_prateritum'),

 path('dass.html', views.dass_view, name='dass'),
 path('wenn.html', views.wenn_view, name='wenn'),
 path('adjend.html', views.adjend_view, name='adjectiveending'),
  path('comperlativesuperlative.html', views.comperlative_superlative_view, name='comperlativesuperlative'),
path('werden.html', views.werden_view, name='werden'),
path('indirect.html', views.indirect_view, name='indirect'),
path('konjunktiv2.html', views.konjunktiv2_view, name='konjunktiv2'),
path('genetivname.html', views.genetivname_view, name='genetivname'),
path('als.html', views.als_view, name='als'),
path('extrapronomen.html', views.extrapronomen_view, name='extrapronomen'),
path('Interrogativartikel.html', views.Interrogativartikel_view, name='Interrogativartikel'),
path('relativsatz.html', views.relativsatz_view, name='relativsatz'),
path('damitumzu.html', views.damitumzu_view, name='damitumzu'),
path('konjunktivII.html', views.konjunktivII_view, name='konjunktivII'),
path('verbenmitpreposition.html', views.verbenmitpreposition_view, name='verbenmitpreposition'),
path('wfrageprep.html', views.wfrageprep_view, name='wfrageprep'),
path('wfrageprep.html', views.wfrageprep_view, name='wfrageprep'),
path('wfrageprep.html', views.wfrageprep_view, name='wfrageprep'),
path('wfrageprep.html', views.wfrageprep_view, name='wfrageprep'),
path('wfrageprep.html', views.wfrageprep_view, name='wfrageprep'),


path('b1-topics.html', views.b1_topics_view, name='b1-topic'),
path('infinitiv-zu.html', views.infinitiv_zu, name='infinitiv-zu'),
path('lassen.html', views.lassen, name='lassen'),
path('obwohl.html', views.obwohl, name='obwohl'),
path('genitiv.html', views.genitiv, name='genitiv'),
path('wegen-trotz.html', views.wegen_trotz, name='wegen-trotz'),
path('praeteritum.html', views.praeteritum, name='praeteritum'),
path('temp-praep.html', views.temp_praep, name='temp-praep'),
path('deshalb-darum.html', views.deshalb_darum, name='deshalb-darum'),
path('sodass.html', views.sodass, name='sodass'),
path('konj2.html', views.konj2, name='konj2'),
path('pronomen-praep.html', views.pronomen_praep, name='pronomen-praep'),
path('verben-praep.html', views.verben_praep, name='verben-praep'),
path('komp-super.html', views.komp_super, name='komp-super'),
path('aus-material.html', views.aus_material, name='aus-material'),
path('relativ-dativ.html', views.relativ_dativ, name='relativ-dativ'),
path('relativ-praep.html', views.relativ_praep, name='relativ-praep'),
path('plusquam.html', views.plusquam, name='plusquam'),
path('temp-neben.html', views.temp_neben, name='temp-neben'),
path('brauchen-zu.html', views.brauchen_zu, name='brauchen-zu'),
path('reflexiv.html', views.reflexiv, name='reflexiv'),
path('konnektoren.html', views.konnektoren, name='konnektoren'),
path('adj-ohne-art.html', views.adj_ohne_art, name='adj-ohne-art'),
path('passiv.html', views.passiv, name='passiv'),
path('passiv-modal.html', views.passiv_modal, name='passiv-modal'),
path('genitiv-praep.html', views.genitiv_praep, name='genitiv-praep'),
path('artikelpronomen.html', views.artikelpronomen, name='artikelpronomen'),
path('relativ-was-wo.html', views.relativ_was_wo, name='relativ-was-wo'),
path('je-desto.html', views.je_desto, name='je-desto'),
path('partizip-adj.html', views.partizip_adj, name='partizip-adj'),
path('n-dekl.html', views.n_dekl, name='n-dekl'),
path('exam1.html', views.exam1, name='exam1'),

path('exam2.html', views.exam2, name='exam2'),
path('exam3.html', views.exam3, name='exam3'),
path('exam4.html', views.exam4, name='exam4'),
path('exam5.html', views.exam5, name='exam5'),
path('exam6.html', views.exam6, name='exam6'),
path('exam7.html', views.exam7, name='exam7'),
path('exam8.html', views.exam8, name='exam8'),
path('exam9.html', views.exam9, name='exam9'),
path('exam10.html', views.exam10, name='exam10'),





path('schreibenb1.html', views.schreibenb1, name='schreibenb1'),
path('schreibenb1m2.html', views.schreibenb1m2, name='schreibenb1m2'),
path('schreibenb1m3.html', views.schreibenb1m3, name='schreibenb1m3'),
path('schreibenb1m4.html', views.schreibenb1m4, name='schreibenb1m4'),
path('schreibenb1m5.html', views.schreibenb1m5, name='schreibenb1m5'),
path('schreibenb1m6.html', views.schreibenb1m6, name='schreibenb1m6'),
path('schreibenb1m7.html', views.schreibenb1m7, name='schreibenb1m7'),
path('schreibenb1m8.html', views.schreibenb1m8, name='schreibenb1m8'),
path('schreibenb1m9.html', views.schreibenb1m9, name='schreibenb1m9'),
path('schreibenb1m10.html', views.schreibenb1m10, name='schreibenb1m10'),

path('practice_Exam.html', views.practiceExam, name='practice_Exam'),
path('sprechenb1m1.html', views.sprechenb1m1, name='sprechenb1m1'),
path('sprechenb1m2.html', views.sprechenb1m2, name='sprechenb1m2'),
path('sprechenb1m3.html', views.sprechenb1m3, name='sprechenb1m3'),
path('sprechenb1m4.html', views.sprechenb1m4, name='sprechenb1m4'),
path('sprechenb1m5.html', views.sprechenb1m5, name='sprechenb1m5'),
path('sprechenb1m6.html', views.sprechenb1m6, name='sprechenb1m6'),
path('sprechenb1m7.html', views.sprechenb1m7, name='sprechenb1m7'),
path('sprechenb1m8.html', views.sprechenb1m8, name='sprechenb1m8'),
path('sprechenb1m9.html', views.sprechenb1m9, name='sprechenb1m9'),
path('sprechenb1m10.html', views.sprechenb1m10, name='sprechenb1m10'),






]
